<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Appmerce\Buckaroo\Block\Info\Ideal
 */
$additionalInformation = $block->getInfo()->getAdditionalInformation();
?>
<?php foreach ($additionalInformation as $key => $value): ?>
    <?php echo $block->escapeHtml($key . ': ' . $value) ?>
        {{pdf_row_separator}}
<?php endforeach; ?>